"""
Модуль для маппинга подтипов одежды на русский язык

Содержит расширенный словарь переводов для всех типов одежды:
- Верхняя одежда (OUTERWEAR)
- Свитеры и кофты (INNERWEAR)
- Рубашки и топы (BODYWEAR)
- Платья и комбинезоны (FULLBODY)
- Штаны и брюки (LEGWEAR)
- Обувь (FOOTWEAR)
- Головные уборы (HEADWEAR)
- Аксессуары (ACCESSORIES)
"""


def map_subtype_to_russian(subtype_input: str) -> str:
    """
    Маппинг английского подтипа одежды на русский язык

    Args:
        subtype_input: Подтип одежды на английском

    Returns:
        Подтип на русском языке
    """
    normalized = subtype_input.lower().strip()

    # Subtype mapping dictionary - расширенная версия
    subtype_map = {
        # === ВЕРХНЯЯ ОДЕЖДА (OUTERWEAR) ===
        'coat': 'Пальто',
        'overcoat': 'Пальто',
        'winter coat': 'Зимнее пальто',
        'wool coat': 'Шерстяное пальто',
        'peacoat': 'Бушлат',
        'trench coat': 'Тренч',
        'trenchcoat': 'Тренч',
        'raincoat': 'Дождевик',
        'mac': 'Макинтош',
        
        'jacket': 'Куртка',
        'blazer': 'Блейзер',
        'sport coat': 'Спортивный пиджак',
        'suit jacket': 'Пиджак от костюма',
        'bomber': 'Бомбер',
        'bomber jacket': 'Бомбер',
        'flight jacket': 'Летная куртка',
        'parka': 'Парка',
        'anorak': 'Анорак',
        'windbreaker': 'Ветровка',
        'windcheater': 'Ветровка',
        'track jacket': 'Спортивная куртка',
        'varsity jacket': 'Университетская куртка',
        'letterman jacket': 'Университетская куртка',
        
        'denim jacket': 'Джинсовая куртка',
        'jean jacket': 'Джинсовая куртка',
        'leather jacket': 'Кожаная куртка',
        'moto jacket': 'Мотокуртка',
        'biker jacket': 'Байкерская куртка',
        'motorcycle jacket': 'Мотокуртка',
        'suede jacket': 'Замшевая куртка',
        
        'vest': 'Жилет',
        'waistcoat': 'Жилет',
        'gilet': 'Жилет',
        'puffer vest': 'Пуховый жилет',
        'puffer': 'Пуховик',
        'down vest': 'Пуховый жилет',
        'fleece vest': 'Флисовый жилет',
        
        'puffer jacket': 'Пуховик',
        'down jacket': 'Пуховик',
        'quilted jacket': 'Стеганая куртка',
        'padded jacket': 'Утепленная куртка',
        'insulated jacket': 'Утепленная куртка',
        
        # === СВИТЕРЫ И КОФТЫ (INNERWEAR) ===
        'sweater': 'Свитер',
        'jumper': 'Джемпер',
        'pullover': 'Пуловер',
        'knit': 'Вязаная кофта',
        'knitwear': 'Трикотаж',
        'knit sweater': 'Вязаный свитер',
        
        'cardigan': 'Кардиган',
        'open cardigan': 'Кардиган на пуговицах',
        'button cardigan': 'Кардиган на пуговицах',
        'zip cardigan': 'Кардиган на молнии',
        'long cardigan': 'Длинный кардиган',
        
        'hoodie': 'Худи',
        'hooded sweatshirt': 'Худи',
        'zip hoodie': 'Худи на молнии',
        'pullover hoodie': 'Худи без молнии',
        'sweatshirt': 'Свитшот',
        'crew sweatshirt': 'Свитшот',
        'fleece': 'Флиска',
        'fleece sweatshirt': 'Флисовый свитшот',
        
        'turtleneck': 'Водолазка',
        'turtle neck': 'Водолазка',
        'mock neck': 'Водолазка с невысоким воротом',
        'mock turtleneck': 'Водолазка с невысоким воротом',
        'high neck': 'Высокий ворот',
        
        'crewneck': 'Свитер с круглым вырезом',
        'crew neck': 'Свитер с круглым вырезом',
        'round neck': 'Круглый вырез',
        'v-neck': 'V-образный вырез',
        'v neck': 'V-образный вырез',
        'scoop neck': 'Глубокий вырез',
        'boat neck': 'Лодочка',
        'cowl neck': 'Воротник-хомут',
        
        # === РУБАШКИ И ТОПЫ (BODYWEAR) ===
        't-shirt': 'Футболка',
        'tshirt': 'Футболка',
        'tee': 'Футболка',
        'graphic tee': 'Футболка с принтом',
        'printed tee': 'Футболка с принтом',
        'basic tee': 'Базовая футболка',
        'oversized tee': 'Оверсайз футболка',
        'fitted tee': 'Приталенная футболка',
        'crop tee': 'Укороченная футболка',
        
        'polo': 'Поло',
        'polo shirt': 'Рубашка поло',
        'golf shirt': 'Рубашка поло',
        'tennis shirt': 'Теннисная рубашка',
        
        'shirt': 'Рубашка',
        'dress shirt': 'Классическая рубашка',
        'button-up': 'Рубашка на пуговицах',
        'button up': 'Рубашка на пуговицах',
        'button-down': 'Рубашка с воротником на пуговицах',
        'button down': 'Рубашка с воротником на пуговицах',
        'oxford shirt': 'Оксфордская рубашка',
        'flannel shirt': 'Фланелевая рубашка',
        'flannel': 'Фланель',
        'denim shirt': 'Джинсовая рубашка',
        'chambray shirt': 'Рубашка из шамбре',
        'linen shirt': 'Льняная рубашка',
        'hawaiian shirt': 'Гавайская рубашка',
        'camp shirt': 'Рубашка в стиле кэмп',
        
        'blouse': 'Блузка',
        'silk blouse': 'Шелковая блузка',
        'chiffon blouse': 'Шифоновая блузка',
        'peasant blouse': 'Блузка в крестьянском стиле',
        
        'top': 'Топ',
        'tank top': 'Майка',
        'tank': 'Майка',
        'camisole': 'Камисоль',
        'cami': 'Камисоль',
        'spaghetti strap': 'Топ на тонких бретелях',
        'halter top': 'Топ-халтер',
        'bandeau': 'Бандо',
        'tube top': 'Топ-труба',
        'crop top': 'Укороченный топ',
        'cropped top': 'Укороченный топ',
        'bralette': 'Бралетт',
        'bustier': 'Бюстье',
        'corset': 'Корсет',
        
        'henley': 'Хенли',
        'raglan': 'Реглан',
        'baseball tee': 'Бейсбольная футболка',
        'ringer tee': 'Футболка с контрастной отделкой',
        
        # === ПЛАТЬЯ И КОМБИНЕЗОНЫ (FULLBODY) ===
        'dress': 'Платье',
        'gown': 'Вечернее платье',
        'evening dress': 'Вечернее платье',
        'cocktail dress': 'Коктейльное платье',
        'party dress': 'Платье для вечеринки',
        'formal dress': 'Официальное платье',
        'casual dress': 'Повседневное платье',
        'summer dress': 'Летнее платье',
        'sundress': 'Сарафан',
        'maxi dress': 'Макси платье',
        'midi dress': 'Миди платье',
        'mini dress': 'Мини платье',
        'knee-length dress': 'Платье до колена',
        'floor-length dress': 'Платье в пол',
        'a-line dress': 'Платье А-силуэта',
        'fit and flare': 'Приталенное платье с расклешенной юбкой',
        'bodycon dress': 'Облегающее платье',
        'shift dress': 'Платье-шифт',
        'wrap dress': 'Платье с запахом',
        'shirt dress': 'Платье-рубашка',
        'sweater dress': 'Платье-свитер',
        'knit dress': 'Вязаное платье',
        'slip dress': 'Платье-комбинация',
        'off-shoulder dress': 'Платье с открытыми плечами',
        'strapless dress': 'Платье без бретелей',
        'halter dress': 'Платье-халтер',
        'backless dress': 'Платье с открытой спиной',
        
        'jumpsuit': 'Комбинезон',
        'overall': 'Комбинезон',
        'overalls': 'Комбинезон',
        'coverall': 'Рабочий комбинезон',
        'romper': 'Ромпер',
        'playsuit': 'Комбинезон-шорты',
        'catsuit': 'Комбинезон-кэтсьют',
        'bodysuit': 'Боди',
        'leotard': 'Купальник-боди',
        'unitard': 'Комбинезон-трико',
        
        'skirt': 'Юбка',
        'mini skirt': 'Мини-юбка',
        'midi skirt': 'Миди-юбка',
        'maxi skirt': 'Макси-юбка',
        'a-line skirt': 'Юбка А-силуэта',
        'pencil skirt': 'Юбка-карандаш',
        'pleated skirt': 'Плиссированная юбка',
        'circle skirt': 'Юбка-солнце',
        'wrap skirt': 'Юбка с запахом',
        'denim skirt': 'Джинсовая юбка',
        'leather skirt': 'Кожаная юбка',
        
        # === ШТАНЫ И БРЮКИ (LEGWEAR) ===
        'pants': 'Брюки',
        'trousers': 'Брюки',
        'slacks': 'Брюки',
        'dress pants': 'Классические брюки',
        'formal pants': 'Официальные брюки',
        'suit pants': 'Брюки от костюма',
        'tailored pants': 'Брюки по фигуре',
        'straight pants': 'Прямые брюки',
        'wide-leg pants': 'Широкие брюки',
        'palazzo pants': 'Брюки-палаццо',
        'bootcut pants': 'Брюки с расклешенным низом',
        'flare pants': 'Расклешенные брюки',
        'cropped pants': 'Укороченные брюки',
        'capri pants': 'Капри',
        'ankle pants': 'Брюки до щиколотки',
        'high-waisted pants': 'Брюки с высокой талией',
        'low-rise pants': 'Брюки с низкой посадкой',
        
        'jeans': 'Джинсы',
        'denim': 'Джинсы',
        'skinny jeans': 'Узкие джинсы',
        'slim jeans': 'Зауженные джинсы',
        'straight jeans': 'Прямые джинсы',
        'bootcut jeans': 'Джинсы с расклешенным низом',
        'flare jeans': 'Расклешенные джинсы',
        'wide-leg jeans': 'Широкие джинсы',
        'boyfriend jeans': 'Джинсы бойфренд',
        'girlfriend jeans': 'Джинсы гёрлфренд',
        'mom jeans': 'Джинсы мом',
        'dad jeans': 'Джинсы дэд',
        'high-waisted jeans': 'Джинсы с высокой талией',
        'low-rise jeans': 'Джинсы с низкой посадкой',
        'ripped jeans': 'Рваные джинсы',
        'distressed jeans': 'Потертые джинсы',
        'raw denim': 'Сырой деним',
        'selvedge denim': 'Селвидж деним',
        
        'chinos': 'Чиносы',
        'khakis': 'Хаки',
        'cargo pants': 'Карго',
        'cargo': 'Карго',
        'utility pants': 'Утилитарные брюки',
        'tactical pants': 'Тактические брюки',
        
        'joggers': 'Джоггеры',
        'sweatpants': 'Спортивные штаны',
        'track pants': 'Спортивные брюки',
        'athletic pants': 'Спортивные брюки',
        'yoga pants': 'Брюки для йоги',
        'workout pants': 'Тренировочные брюки',
        
        'leggings': 'Леггинсы',
        'tights': 'Колготки',
        'compression leggings': 'Компрессионные леггинсы',
        'yoga leggings': 'Леггинсы для йоги',
        'athletic leggings': 'Спортивные леггинсы',
        
        'shorts': 'Шорты',
        'bermuda shorts': 'Бермуды',
        'cargo shorts': 'Шорты карго',
        'denim shorts': 'Джинсовые шорты',
        'jean shorts': 'Джинсовые шорты',
        'athletic shorts': 'Спортивные шорты',
        'running shorts': 'Беговые шорты',
        'basketball shorts': 'Баскетбольные шорты',
        'swim shorts': 'Плавательные шорты',
        'board shorts': 'Бордшорты',
        'cycling shorts': 'Велосипедные шорты',
        'bike shorts': 'Велошорты',
        'hot pants': 'Горячие шорты',
        'mini shorts': 'Мини-шорты',
        'high-waisted shorts': 'Шорты с высокой талией',
        
        # === ОБУВЬ (FOOTWEAR) ===
        'shoes': 'Обувь',
        'footwear': 'Обувь',
        
        'sneakers': 'Кроссовки',
        'trainers': 'Кроссовки',
        'brown suede': 'Ботинки',
        'athletic shoes': 'Спортивная обувь',
        'running shoes': 'Беговые кроссовки',
        'tennis shoes': 'Теннисные кроссовки',
        'basketball shoes': 'Баскетбольные кроссовки',
        'skate shoes': 'Скейтерские кроссовки',
        'canvas shoes': 'Кеды',
        'high-top sneakers': 'Высокие кроссовки',
        'low-top sneakers': 'Низкие кроссовки',
        'slip-on sneakers': 'Слипоны',
        
        'boot': 'Ботинки',
        'boots': 'Ботинки',
        'ankle boots': 'Ботильоны',
        'chelsea boots': 'Челси',
        'combat boots': 'Берцы',
        'work boots': 'Рабочие ботинки',
        'hiking boots': 'Треккинговые ботинки',
        'cowboy boots': 'Ковбойские сапоги',
        'western boots': 'Вестерн сапоги',
        'knee-high boots': 'Сапоги до колена',
        'thigh-high boots': 'Ботфорты',
        'over-the-knee boots': 'Ботфорты',
        'rain boots': 'Резиновые сапоги',
        'wellington boots': 'Веллингтоны',
        'snow boots': 'Зимние сапоги',
        'ugg boots': 'Угги',
        'desert boots': 'Дезерты',
        'chukka boots': 'Чукка',
        'doc martens': 'Доктор Мартинс',
        'dr martens': 'Доктор Мартинс',
        
        'dress shoes': 'Классическая обувь',
        'formal shoes': 'Официальная обувь',
        'oxfords': 'Оксфорды',
        'brogues': 'Броги',
        'derbies': 'Дерби',
        'loafers': 'Лоферы',
        'penny loafers': 'Пенни лоферы',
        'tassel loafers': 'Лоферы с кисточками',
        'boat shoes': 'Топсайдеры',
        'deck shoes': 'Палубная обувь',
        'moccasins': 'Мокасины',
        'driving shoes': 'Мокасины для вождения',
        
        'heels': 'Туфли на каблуке',
        'high heels': 'Высокий каблук',
        'stilettos': 'Шпильки',
        'pumps': 'Лодочки',
        'kitten heels': 'Низкий каблук',
        'block heels': 'Устойчивый каблук',
        'wedges': 'Танкетка',
        'platform shoes': 'Платформа',
        
        'flats': 'Балетки',
        'ballet flats': 'Балетки',
        'pointed flats': 'Балетки с острым носом',
        'round toe flats': 'Балетки с круглым носом',
        'mary janes': 'Мэри Джейн',
        
        'sandals': 'Сандалии',
        'flip-flops': 'Вьетнамки',
        'slides': 'Шлепанцы',
        'gladiator sandals': 'Гладиаторы',
        'strappy sandals': 'Сандалии с ремешками',
        'platform sandals': 'Сандалии на платформе',
        'wedge sandals': 'Сандалии на танкетке',
        'espadrilles': 'Эспадрильи',
        
        'slippers': 'Тапочки',
        'house shoes': 'Домашняя обувь',
        'mules': 'Мюли',
        'clogs': 'Сабо',
        
        # === ГОЛОВНЫЕ УБОРЫ (HEADWEAR) ===
        'hat': 'Шляпа',
        'cap': 'Кепка',
        'beanie': 'Шапка',
        'knit hat': 'Вязаная шапка',
        'winter hat': 'Зимняя шапка',
        'wool hat': 'Шерстяная шапка',
        'baseball cap': 'Бейсболка',
        'snapback': 'Снэпбэк',
        'trucker hat': 'Кепка дальнобойщика',
        'dad hat': 'Кепка дэд',
        'bucket hat': 'Панама',
        'sun hat': 'Шляпа от солнца',
        'wide-brim hat': 'Широкополая шляпа',
        'fedora': 'Федора',
        'panama hat': 'Панама',
        'cowboy hat': 'Ковбойская шляпа',
        'beret': 'Берет',
        'newsboy cap': 'Кепка газетчика',
        'flat cap': 'Плоская кепка',
        'visor': 'Козырек',
        'headband': 'Повязка на голову',
        'bandana': 'Бандана',
        'turban': 'Тюрбан',
        'hijab': 'Хиджаб',
        'scarf': 'Платок',
        'head scarf': 'Головной платок',
        
        # === АКСЕССУАРЫ (ACCESSORIES) ===
        'bag': 'Сумка',
        'handbag': 'Сумочка',
        'purse': 'Кошелек-сумочка',
        'tote bag': 'Сумка-тоут',
        'shoulder bag': 'Сумка через плечо',
        'crossbody bag': 'Сумка через плечо',
        'messenger bag': 'Мессенджер',
        'satchel': 'Портфель',
        'briefcase': 'Дипломат',
        'backpack': 'Рюкзак',
        'daypack': 'Дневной рюкзак',
        'hiking backpack': 'Туристический рюкзак',
        'laptop bag': 'Сумка для ноутбука',
        'duffel bag': 'Спортивная сумка',
        'gym bag': 'Спортивная сумка',
        'travel bag': 'Дорожная сумка',
        'weekend bag': 'Сумка выходного дня',
        'clutch': 'Клатч',
        'evening bag': 'Вечерняя сумочка',
        'fanny pack': 'Поясная сумка',
        'belt bag': 'Поясная сумка',
        'waist bag': 'Поясная сумка',
        
        'belt': 'Ремень',
        'leather belt': 'Кожаный ремень',
        'fabric belt': 'Тканевый ремень',
        'chain belt': 'Цепочка-ремень',
        'wide belt': 'Широкий ремень',
        'skinny belt': 'Тонкий ремень',
        'dress belt': 'Классический ремень',
        'casual belt': 'Повседневный ремень',
        
        'scarf': 'Шарф',
        'neck scarf': 'Шейный платок',
        'silk scarf': 'Шелковый платок',
        'winter scarf': 'Зимний шарф',
        'infinity scarf': 'Шарф-снуд',
        'pashmina': 'Пашмина',
        'shawl': 'Шаль',
        'wrap': 'Накидка',
        'stole': 'Палантин',
        
        'sunglasses': 'Солнцезащитные очки',
        'glasses': 'Очки',
        'eyeglasses': 'Очки для зрения',
        'reading glasses': 'Очки для чтения',
        'aviators': 'Авиаторы',
        'wayfarers': 'Вейфареры',
        'cat-eye glasses': 'Очки кошачий глаз',
        
        'watch': 'Часы',
        'wristwatch': 'Наручные часы',
        'smartwatch': 'Умные часы',
        'digital watch': 'Цифровые часы',
        'analog watch': 'Аналоговые часы',
        'sports watch': 'Спортивные часы',
        'dress watch': 'Классические часы',
        
        'gloves': 'Перчатки',
        'mittens': 'Варежки',
        'fingerless gloves': 'Перчатки без пальцев',
        'leather gloves': 'Кожаные перчатки',
        'wool gloves': 'Шерстяные перчатки',
        'winter gloves': 'Зимние перчатки',
        'driving gloves': 'Перчатки для вождения',
        
        'jewelry': 'Украшения',
        'necklace': 'Ожерелье',
        'chain': 'Цепочка',
        'pendant': 'Кулон',
        'choker': 'Чокер',
        'earrings': 'Серьги',
        'studs': 'Гвоздики',
        'hoops': 'Кольца',
        'drop earrings': 'Висячие серьги',
        'bracelet': 'Браслет',
        'bangle': 'Жесткий браслет',
        'charm bracelet': 'Браслет с подвесками',
        'ring': 'Кольцо',
        'wedding ring': 'Обручальное кольцо',
        'engagement ring': 'Помолвочное кольцо',
        'brooch': 'Брошь',
        'pin': 'Значок',
        
        'tie': 'Галстук',
        'necktie': 'Галстук',
        'bow tie': 'Бабочка',
        'ascot': 'Аскот',
        'cravat': 'Шейный платок',
        'pocket square': 'Нагрудный платок',
        
        'socks': 'Носки',
        'ankle socks': 'Короткие носки',
        'crew socks': 'Носки до середины голени',
        'knee-high socks': 'Гольфы',
        'thigh-high socks': 'Чулки',
        'stockings': 'Чулки',
        'pantyhose': 'Колготки',
        'compression socks': 'Компрессионные носки',
        'athletic socks': 'Спортивные носки',
        'dress socks': 'Классические носки',
        'wool socks': 'Шерстяные носки',
        'cotton socks': 'Хлопковые носки',
    }

    # Проверяем точное совпадение
    if normalized in subtype_map:
        return subtype_map[normalized]

    # Проверяем частичное совпадение (если в описании есть ключевое слово)
    for eng, rus in subtype_map.items():
        if eng in normalized:
            return rus

    # Если не нашли перевод, возвращаем оригинал
    return subtype_input
