version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: telegramstyle-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../client:/usr/share/nginx/html:ro
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../ssl/certs:/etc/ssl/certs:ro
      - ../ssl/keys:/etc/ssl/keys:ro
    networks:
      - telegramstyle-network
    depends_on:
      - app

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: telegramstyle-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8443
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DOMAIN=${DOMAIN}
      - APP_URL=${APP_URL}
    volumes:
      - ../server:/app
      - /app/node_modules
      - ../ssl:/app/ssl:ro
      - ../client:/app/public:ro
    networks:
      - telegramstyle-network

networks:
  telegramstyle-network:
    driver: bridge

volumes:
  mongodb_data: 